export const options = [
  { value: "city-1", label: "Грозный" },
  { value: "city-2", label: "Москва" },
  { value: "city-3", label: "Лондон" },
  { value: "city-4", label: "Санкт-Петербург" },
  { value: "city-5", label: "Нью-йорк" },
];

export const days = [
  {
    day: "Сегодня",
    day_info: "28 авг",
    icon_id: "sun",
    temp_day: "+18",
    temp_night: "+15",
    info: "Облачно",
  },
  {
    day: "Завтра",
    day_info: "29 авг",
    icon_id: "small_rain_sun",
    temp_day: "+18",
    temp_night: "+15",
    info: "небольшой дождь и солнце",
  },
  {
    day: "Ср",
    day_info: "30 авг",
    icon_id: "small_rain",
    temp_day: "+18",
    temp_night: "+15",
    info: "небольшой дождь",
  },
  {
    day: "Чт",
    day_info: "28 авг",
    icon_id: "mainly_cloudy",
    temp_day: "+18",
    temp_night: "+15",
    info: "Облачно",
  },
  {
    day: "Пт",
    day_info: "28 авг",
    icon_id: "rain",
    temp_day: "+18",
    temp_night: "+15",
    info: "Облачно",
  },
  {
    day: "Сб",
    day_info: "28 авг",
    icon_id: "sun",
    temp_day: "+18",
    temp_night: "+15",
    info: "Облачно",
  },
  {
    day: "Вс",
    day_info: "28 авг",
    icon_id: "sun",
    temp_day: "+18",
    temp_night: "+15",
    info: "Облачно",
  },
];
